// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: engine/v1/engine.proto

package enginev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EngineService_Connect_FullMethodName                 = "/engine.v1.EngineService/Connect"
	EngineService_Disconnect_FullMethodName              = "/engine.v1.EngineService/Disconnect"
	EngineService_Execute_FullMethodName                 = "/engine.v1.EngineService/Execute"
	EngineService_StartConnectSession_FullMethodName     = "/engine.v1.EngineService/StartConnectSession"
	EngineService_GetConnection_FullMethodName           = "/engine.v1.EngineService/GetConnection"
	EngineService_ListConnectionResources_FullMethodName = "/engine.v1.EngineService/ListConnectionResources"
	EngineService_SubscribeWebhooks_FullMethodName       = "/engine.v1.EngineService/SubscribeWebhooks"
)

// EngineServiceClient is the client API for EngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EngineServiceClient interface {
	// Connect performs the SDK handshake: it authenticates the artifact_id and loads
	// the SDK's scope manifest + every referenced Fused object into the Engine's
	// connection-scoped, refcounted cache (AD-7). It must be called once after the
	// SDK opens its long-lived channel and before any Execute call.
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	// Disconnect releases the SDK's cache references. It must be called when the
	// SDK closes its channel so refcounts decrement and objects can be evicted.
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error)
	// Execute an integration endpoint through the Engine.
	// The response is streamed to support server-sent events (SSE) and pagination automatically.
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteResponse], error)
	// StartConnectSession creates an Engine-owned OAuth/OIDC browser session and
	// returns only the provider authorization URL. Client credentials, PKCE
	// verifier, and future token material stay inside the Engine.
	StartConnectSession(ctx context.Context, in *StartConnectSessionRequest, opts ...grpc.CallOption) (*StartConnectSessionResponse, error)
	// GetConnection reads non-sensitive connection metadata after the browser
	// callback redirects with a connection_id. Provider tokens are never returned.
	GetConnection(ctx context.Context, in *GetConnectionRequest, opts ...grpc.CallOption) (*GetConnectionResponse, error)
	// ListConnectionResources returns non-sensitive tenant routing metadata for
	// an opaque connection owned by one of the authenticated SDK's buckets.
	ListConnectionResources(ctx context.Context, in *ListConnectionResourcesRequest, opts ...grpc.CallOption) (*ListConnectionResourcesResponse, error)
	// SubscribeWebhooks opens a durable, receiver-scoped inbound event stream
	// over the same channel used for Execute -- replacing the separate
	// wss://.../sdks/ws WebSocket transport. Auth (x-api-key + x-artifact-id)
	// travels as call metadata, same as every other RPC on this service, not
	// as fields on the first message. The client sends exactly one
	// WebhookSubscribe message first (receiver name + subscribed event types),
	// then zero or more WebhookAck/WebhookNack messages as it processes pushed
	// events. The server pushes WebhookEvent messages for any event matching
	// an active subscription and redelivers un-acked events with backoff --
	// this is a transport change only: durability/retry/queue-group fan-out is
	// unchanged, owned by the Engine's NATS JetStream durable consumer keyed
	// on receiver_name (see websocket_handler.go's setupWebhookConsumer,
	// ported as-is onto this stream in the gRPC handler).
	SubscribeWebhooks(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WebhookClientMessage, WebhookServerMessage], error)
}

type engineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEngineServiceClient(cc grpc.ClientConnInterface) EngineServiceClient {
	return &engineServiceClient{cc}
}

func (c *engineServiceClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, EngineService_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectResponse)
	err := c.cc.Invoke(ctx, EngineService_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EngineService_ServiceDesc.Streams[0], EngineService_Execute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteRequest, ExecuteResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_ExecuteClient = grpc.ServerStreamingClient[ExecuteResponse]

func (c *engineServiceClient) StartConnectSession(ctx context.Context, in *StartConnectSessionRequest, opts ...grpc.CallOption) (*StartConnectSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartConnectSessionResponse)
	err := c.cc.Invoke(ctx, EngineService_StartConnectSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) GetConnection(ctx context.Context, in *GetConnectionRequest, opts ...grpc.CallOption) (*GetConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnectionResponse)
	err := c.cc.Invoke(ctx, EngineService_GetConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) ListConnectionResources(ctx context.Context, in *ListConnectionResourcesRequest, opts ...grpc.CallOption) (*ListConnectionResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConnectionResourcesResponse)
	err := c.cc.Invoke(ctx, EngineService_ListConnectionResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) SubscribeWebhooks(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WebhookClientMessage, WebhookServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EngineService_ServiceDesc.Streams[1], EngineService_SubscribeWebhooks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WebhookClientMessage, WebhookServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_SubscribeWebhooksClient = grpc.BidiStreamingClient[WebhookClientMessage, WebhookServerMessage]

// EngineServiceServer is the server API for EngineService service.
// All implementations must embed UnimplementedEngineServiceServer
// for forward compatibility.
type EngineServiceServer interface {
	// Connect performs the SDK handshake: it authenticates the artifact_id and loads
	// the SDK's scope manifest + every referenced Fused object into the Engine's
	// connection-scoped, refcounted cache (AD-7). It must be called once after the
	// SDK opens its long-lived channel and before any Execute call.
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	// Disconnect releases the SDK's cache references. It must be called when the
	// SDK closes its channel so refcounts decrement and objects can be evicted.
	Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error)
	// Execute an integration endpoint through the Engine.
	// The response is streamed to support server-sent events (SSE) and pagination automatically.
	Execute(*ExecuteRequest, grpc.ServerStreamingServer[ExecuteResponse]) error
	// StartConnectSession creates an Engine-owned OAuth/OIDC browser session and
	// returns only the provider authorization URL. Client credentials, PKCE
	// verifier, and future token material stay inside the Engine.
	StartConnectSession(context.Context, *StartConnectSessionRequest) (*StartConnectSessionResponse, error)
	// GetConnection reads non-sensitive connection metadata after the browser
	// callback redirects with a connection_id. Provider tokens are never returned.
	GetConnection(context.Context, *GetConnectionRequest) (*GetConnectionResponse, error)
	// ListConnectionResources returns non-sensitive tenant routing metadata for
	// an opaque connection owned by one of the authenticated SDK's buckets.
	ListConnectionResources(context.Context, *ListConnectionResourcesRequest) (*ListConnectionResourcesResponse, error)
	// SubscribeWebhooks opens a durable, receiver-scoped inbound event stream
	// over the same channel used for Execute -- replacing the separate
	// wss://.../sdks/ws WebSocket transport. Auth (x-api-key + x-artifact-id)
	// travels as call metadata, same as every other RPC on this service, not
	// as fields on the first message. The client sends exactly one
	// WebhookSubscribe message first (receiver name + subscribed event types),
	// then zero or more WebhookAck/WebhookNack messages as it processes pushed
	// events. The server pushes WebhookEvent messages for any event matching
	// an active subscription and redelivers un-acked events with backoff --
	// this is a transport change only: durability/retry/queue-group fan-out is
	// unchanged, owned by the Engine's NATS JetStream durable consumer keyed
	// on receiver_name (see websocket_handler.go's setupWebhookConsumer,
	// ported as-is onto this stream in the gRPC handler).
	SubscribeWebhooks(grpc.BidiStreamingServer[WebhookClientMessage, WebhookServerMessage]) error
	mustEmbedUnimplementedEngineServiceServer()
}

// UnimplementedEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEngineServiceServer struct{}

func (UnimplementedEngineServiceServer) Connect(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedEngineServiceServer) Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedEngineServiceServer) Execute(*ExecuteRequest, grpc.ServerStreamingServer[ExecuteResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedEngineServiceServer) StartConnectSession(context.Context, *StartConnectSessionRequest) (*StartConnectSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartConnectSession not implemented")
}
func (UnimplementedEngineServiceServer) GetConnection(context.Context, *GetConnectionRequest) (*GetConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConnection not implemented")
}
func (UnimplementedEngineServiceServer) ListConnectionResources(context.Context, *ListConnectionResourcesRequest) (*ListConnectionResourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConnectionResources not implemented")
}
func (UnimplementedEngineServiceServer) SubscribeWebhooks(grpc.BidiStreamingServer[WebhookClientMessage, WebhookServerMessage]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeWebhooks not implemented")
}
func (UnimplementedEngineServiceServer) mustEmbedUnimplementedEngineServiceServer() {}
func (UnimplementedEngineServiceServer) testEmbeddedByValue()                       {}

// UnsafeEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngineServiceServer will
// result in compilation errors.
type UnsafeEngineServiceServer interface {
	mustEmbedUnimplementedEngineServiceServer()
}

func RegisterEngineServiceServer(s grpc.ServiceRegistrar, srv EngineServiceServer) {
	// If the following call pancis, it indicates UnimplementedEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EngineService_ServiceDesc, srv)
}

func _EngineService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EngineServiceServer).Execute(m, &grpc.GenericServerStream[ExecuteRequest, ExecuteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_ExecuteServer = grpc.ServerStreamingServer[ExecuteResponse]

func _EngineService_StartConnectSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartConnectSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).StartConnectSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_StartConnectSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).StartConnectSession(ctx, req.(*StartConnectSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_GetConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).GetConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_GetConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).GetConnection(ctx, req.(*GetConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_ListConnectionResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConnectionResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).ListConnectionResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_ListConnectionResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).ListConnectionResources(ctx, req.(*ListConnectionResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_SubscribeWebhooks_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EngineServiceServer).SubscribeWebhooks(&grpc.GenericServerStream[WebhookClientMessage, WebhookServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_SubscribeWebhooksServer = grpc.BidiStreamingServer[WebhookClientMessage, WebhookServerMessage]

// EngineService_ServiceDesc is the grpc.ServiceDesc for EngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "engine.v1.EngineService",
	HandlerType: (*EngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _EngineService_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _EngineService_Disconnect_Handler,
		},
		{
			MethodName: "StartConnectSession",
			Handler:    _EngineService_StartConnectSession_Handler,
		},
		{
			MethodName: "GetConnection",
			Handler:    _EngineService_GetConnection_Handler,
		},
		{
			MethodName: "ListConnectionResources",
			Handler:    _EngineService_ListConnectionResources_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Execute",
			Handler:       _EngineService_Execute_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeWebhooks",
			Handler:       _EngineService_SubscribeWebhooks_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "engine/v1/engine.proto",
}
