// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: engine/v1/engine.proto

package enginev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_engine_v1_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ConnectRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_engine_v1_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{1}
}

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_engine_v1_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{2}
}

func (x *DisconnectRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type DisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_engine_v1_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{3}
}

type ExecuteRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AppId        string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Token        string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	EndpointName string                 `protobuf:"bytes,3,opt,name=endpoint_name,json=endpointName,proto3" json:"endpoint_name,omitempty"`
	Params       []byte                 `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"` // JSON-encoded parameters
	// credentials is the per-request passthrough auth material forwarded from the
	// SDK config to the Engine and used in-flight only (never persisted). Keys
	// match what applyAuth expects: "Authorization", "username"/"password", or the
	// apiKey key name for the provider.
	Credentials map[string]string `protobuf:"bytes,5,rep,name=credentials,proto3" json:"credentials,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// environment is the provider-specific runtime environment name selected for
	// this request, such as "sandbox" or "eu". It is never a URL.
	Environment string `protobuf:"bytes,6,opt,name=environment,proto3" json:"environment,omitempty"`
	// idempotency_key is generated by the SDK once per logical request so
	// Engine/provider retries share a cap without hidden SDK-side replay.
	IdempotencyKey string `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// request_body_hash is the SHA-256 hex digest of the exact JSON params bytes
	// sent by the SDK for this Execute call.
	RequestBodyHash string `protobuf:"bytes,8,opt,name=request_body_hash,json=requestBodyHash,proto3" json:"request_body_hash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_engine_v1_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ExecuteRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ExecuteRequest) GetEndpointName() string {
	if x != nil {
		return x.EndpointName
	}
	return ""
}

func (x *ExecuteRequest) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ExecuteRequest) GetCredentials() map[string]string {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *ExecuteRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ExecuteRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ExecuteRequest) GetRequestBodyHash() string {
	if x != nil {
		return x.RequestBodyHash
	}
	return ""
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []byte                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`                            // JSON-encoded response chunk or full response
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                              // Optional error message
	StatusCode    int32                  `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // Provider HTTP status, sent once after response chunks
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_engine_v1_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

type StartConnectSessionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BucketId       string                 `protobuf:"bytes,1,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	ServiceId      string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	EndUserRef     string                 `protobuf:"bytes,3,opt,name=end_user_ref,json=endUserRef,proto3" json:"end_user_ref,omitempty"`
	ReturnUrl      string                 `protobuf:"bytes,4,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	CreatedByAppId string                 `protobuf:"bytes,5,opt,name=created_by_app_id,json=createdByAppId,proto3" json:"created_by_app_id,omitempty"`
	// resource_input carries only fields declared by x-fused-connect; Engine
	// validates and binds them to callback state before provider redirect.
	ResourceInput map[string]string `protobuf:"bytes,6,rep,name=resource_input,json=resourceInput,proto3" json:"resource_input,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// scopes narrows provider consent to service-declared OAuth/OIDC scopes.
	Scopes        []string `protobuf:"bytes,7,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartConnectSessionRequest) Reset() {
	*x = StartConnectSessionRequest{}
	mi := &file_engine_v1_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartConnectSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartConnectSessionRequest) ProtoMessage() {}

func (x *StartConnectSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartConnectSessionRequest.ProtoReflect.Descriptor instead.
func (*StartConnectSessionRequest) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{6}
}

func (x *StartConnectSessionRequest) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *StartConnectSessionRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *StartConnectSessionRequest) GetEndUserRef() string {
	if x != nil {
		return x.EndUserRef
	}
	return ""
}

func (x *StartConnectSessionRequest) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *StartConnectSessionRequest) GetCreatedByAppId() string {
	if x != nil {
		return x.CreatedByAppId
	}
	return ""
}

func (x *StartConnectSessionRequest) GetResourceInput() map[string]string {
	if x != nil {
		return x.ResourceInput
	}
	return nil
}

func (x *StartConnectSessionRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type StartConnectSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorizeUrl  string                 `protobuf:"bytes,1,opt,name=authorize_url,json=authorizeUrl,proto3" json:"authorize_url,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartConnectSessionResponse) Reset() {
	*x = StartConnectSessionResponse{}
	mi := &file_engine_v1_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartConnectSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartConnectSessionResponse) ProtoMessage() {}

func (x *StartConnectSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartConnectSessionResponse.ProtoReflect.Descriptor instead.
func (*StartConnectSessionResponse) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{7}
}

func (x *StartConnectSessionResponse) GetAuthorizeUrl() string {
	if x != nil {
		return x.AuthorizeUrl
	}
	return ""
}

func (x *StartConnectSessionResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type GetConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionRequest) Reset() {
	*x = GetConnectionRequest{}
	mi := &file_engine_v1_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionRequest) ProtoMessage() {}

func (x *GetConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionRequest.ProtoReflect.Descriptor instead.
func (*GetConnectionRequest) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{8}
}

func (x *GetConnectionRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type GetConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connection    *AuthConnection        `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionResponse) Reset() {
	*x = GetConnectionResponse{}
	mi := &file_engine_v1_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionResponse) ProtoMessage() {}

func (x *GetConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionResponse.ProtoReflect.Descriptor instead.
func (*GetConnectionResponse) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{9}
}

func (x *GetConnectionResponse) GetConnection() *AuthConnection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *GetConnectionResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type AuthConnection struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BucketId              string                 `protobuf:"bytes,2,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	ServiceId             string                 `protobuf:"bytes,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	EndUserRef            string                 `protobuf:"bytes,4,opt,name=end_user_ref,json=endUserRef,proto3" json:"end_user_ref,omitempty"`
	CreatedByAppId        string                 `protobuf:"bytes,5,opt,name=created_by_app_id,json=createdByAppId,proto3" json:"created_by_app_id,omitempty"`
	AuthType              string                 `protobuf:"bytes,6,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"`
	TokenType             string                 `protobuf:"bytes,7,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	Scopes                []string               `protobuf:"bytes,8,rep,name=scopes,proto3" json:"scopes,omitempty"`
	ScopeSource           string                 `protobuf:"bytes,9,opt,name=scope_source,json=scopeSource,proto3" json:"scope_source,omitempty"`
	Issuer                string                 `protobuf:"bytes,10,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Subject               string                 `protobuf:"bytes,11,opt,name=subject,proto3" json:"subject,omitempty"`
	ExpiresAt             string                 `protobuf:"bytes,12,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	RefreshTokenExpiresAt string                 `protobuf:"bytes,13,opt,name=refresh_token_expires_at,json=refreshTokenExpiresAt,proto3" json:"refresh_token_expires_at,omitempty"`
	LastUsedAt            string                 `protobuf:"bytes,14,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	RefreshState          string                 `protobuf:"bytes,15,opt,name=refresh_state,json=refreshState,proto3" json:"refresh_state,omitempty"`
	CreatedAt             string                 `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             string                 `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AuthConnection) Reset() {
	*x = AuthConnection{}
	mi := &file_engine_v1_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthConnection) ProtoMessage() {}

func (x *AuthConnection) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthConnection.ProtoReflect.Descriptor instead.
func (*AuthConnection) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{10}
}

func (x *AuthConnection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuthConnection) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *AuthConnection) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *AuthConnection) GetEndUserRef() string {
	if x != nil {
		return x.EndUserRef
	}
	return ""
}

func (x *AuthConnection) GetCreatedByAppId() string {
	if x != nil {
		return x.CreatedByAppId
	}
	return ""
}

func (x *AuthConnection) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *AuthConnection) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *AuthConnection) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *AuthConnection) GetScopeSource() string {
	if x != nil {
		return x.ScopeSource
	}
	return ""
}

func (x *AuthConnection) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *AuthConnection) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AuthConnection) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *AuthConnection) GetRefreshTokenExpiresAt() string {
	if x != nil {
		return x.RefreshTokenExpiresAt
	}
	return ""
}

func (x *AuthConnection) GetLastUsedAt() string {
	if x != nil {
		return x.LastUsedAt
	}
	return ""
}

func (x *AuthConnection) GetRefreshState() string {
	if x != nil {
		return x.RefreshState
	}
	return ""
}

func (x *AuthConnection) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AuthConnection) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListConnectionResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectionResourcesRequest) Reset() {
	*x = ListConnectionResourcesRequest{}
	mi := &file_engine_v1_engine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectionResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectionResourcesRequest) ProtoMessage() {}

func (x *ListConnectionResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectionResourcesRequest.ProtoReflect.Descriptor instead.
func (*ListConnectionResourcesRequest) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{11}
}

func (x *ListConnectionResourcesRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type ListConnectionResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*ConnectionResource  `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectionResourcesResponse) Reset() {
	*x = ListConnectionResourcesResponse{}
	mi := &file_engine_v1_engine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectionResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectionResourcesResponse) ProtoMessage() {}

func (x *ListConnectionResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectionResourcesResponse.ProtoReflect.Descriptor instead.
func (*ListConnectionResourcesResponse) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{12}
}

func (x *ListConnectionResourcesResponse) GetResources() []*ConnectionResource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type ConnectionResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConnectionId  string                 `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ResourceType  string                 `protobuf:"bytes,4,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	DisplayName   string                 `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Scopes        []string               `protobuf:"bytes,6,rep,name=scopes,proto3" json:"scopes,omitempty"`
	IsDefault     bool                   `protobuf:"varint,7,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionResource) Reset() {
	*x = ConnectionResource{}
	mi := &file_engine_v1_engine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionResource) ProtoMessage() {}

func (x *ConnectionResource) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionResource.ProtoReflect.Descriptor instead.
func (*ConnectionResource) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{13}
}

func (x *ConnectionResource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConnectionResource) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ConnectionResource) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ConnectionResource) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ConnectionResource) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ConnectionResource) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *ConnectionResource) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *ConnectionResource) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ConnectionResource) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type WebhookClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WebhookClientMessage_Subscribe
	//	*WebhookClientMessage_Ack
	//	*WebhookClientMessage_Nack
	Payload       isWebhookClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookClientMessage) Reset() {
	*x = WebhookClientMessage{}
	mi := &file_engine_v1_engine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookClientMessage) ProtoMessage() {}

func (x *WebhookClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookClientMessage.ProtoReflect.Descriptor instead.
func (*WebhookClientMessage) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{14}
}

func (x *WebhookClientMessage) GetPayload() isWebhookClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WebhookClientMessage) GetSubscribe() *WebhookSubscribe {
	if x != nil {
		if x, ok := x.Payload.(*WebhookClientMessage_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *WebhookClientMessage) GetAck() *WebhookAck {
	if x != nil {
		if x, ok := x.Payload.(*WebhookClientMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *WebhookClientMessage) GetNack() *WebhookNack {
	if x != nil {
		if x, ok := x.Payload.(*WebhookClientMessage_Nack); ok {
			return x.Nack
		}
	}
	return nil
}

type isWebhookClientMessage_Payload interface {
	isWebhookClientMessage_Payload()
}

type WebhookClientMessage_Subscribe struct {
	Subscribe *WebhookSubscribe `protobuf:"bytes,1,opt,name=subscribe,proto3,oneof"`
}

type WebhookClientMessage_Ack struct {
	Ack *WebhookAck `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type WebhookClientMessage_Nack struct {
	Nack *WebhookNack `protobuf:"bytes,3,opt,name=nack,proto3,oneof"`
}

func (*WebhookClientMessage_Subscribe) isWebhookClientMessage_Payload() {}

func (*WebhookClientMessage_Ack) isWebhookClientMessage_Payload() {}

func (*WebhookClientMessage_Nack) isWebhookClientMessage_Payload() {}

type WebhookSubscribe struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// receiver_name is the durable NATS consumer/queue-group identity
	// (accountID + "-" + receiver_name server-side) -- intentionally
	// independent of app_id/the Connect session, so the same named
	// receiver can resume across reconnects and multiple processes can share
	// one receiver_name for queue-group fan-out. Auth (app_id + token)
	// is carried as x-api-key/x-app-id call metadata instead of fields
	// here, matching every other RPC on this service.
	ReceiverName  string   `protobuf:"bytes,1,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	Events        []string `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookSubscribe) Reset() {
	*x = WebhookSubscribe{}
	mi := &file_engine_v1_engine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookSubscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookSubscribe) ProtoMessage() {}

func (x *WebhookSubscribe) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookSubscribe.ProtoReflect.Descriptor instead.
func (*WebhookSubscribe) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{15}
}

func (x *WebhookSubscribe) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *WebhookSubscribe) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

type WebhookAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookAck) Reset() {
	*x = WebhookAck{}
	mi := &file_engine_v1_engine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookAck) ProtoMessage() {}

func (x *WebhookAck) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookAck.ProtoReflect.Descriptor instead.
func (*WebhookAck) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{16}
}

func (x *WebhookAck) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type WebhookNack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // optional, for observability
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookNack) Reset() {
	*x = WebhookNack{}
	mi := &file_engine_v1_engine_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookNack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookNack) ProtoMessage() {}

func (x *WebhookNack) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookNack.ProtoReflect.Descriptor instead.
func (*WebhookNack) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{17}
}

func (x *WebhookNack) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *WebhookNack) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type WebhookServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WebhookServerMessage_Subscribed
	//	*WebhookServerMessage_Event
	Payload       isWebhookServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookServerMessage) Reset() {
	*x = WebhookServerMessage{}
	mi := &file_engine_v1_engine_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookServerMessage) ProtoMessage() {}

func (x *WebhookServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookServerMessage.ProtoReflect.Descriptor instead.
func (*WebhookServerMessage) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{18}
}

func (x *WebhookServerMessage) GetPayload() isWebhookServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WebhookServerMessage) GetSubscribed() *WebhookSubscribeAck {
	if x != nil {
		if x, ok := x.Payload.(*WebhookServerMessage_Subscribed); ok {
			return x.Subscribed
		}
	}
	return nil
}

func (x *WebhookServerMessage) GetEvent() *WebhookEvent {
	if x != nil {
		if x, ok := x.Payload.(*WebhookServerMessage_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isWebhookServerMessage_Payload interface {
	isWebhookServerMessage_Payload()
}

type WebhookServerMessage_Subscribed struct {
	Subscribed *WebhookSubscribeAck `protobuf:"bytes,1,opt,name=subscribed,proto3,oneof"` // confirms the subscription took effect
}

type WebhookServerMessage_Event struct {
	Event *WebhookEvent `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

func (*WebhookServerMessage_Subscribed) isWebhookServerMessage_Payload() {}

func (*WebhookServerMessage_Event) isWebhookServerMessage_Payload() {}

type WebhookSubscribeAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiverName  string                 `protobuf:"bytes,1,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookSubscribeAck) Reset() {
	*x = WebhookSubscribeAck{}
	mi := &file_engine_v1_engine_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookSubscribeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookSubscribeAck) ProtoMessage() {}

func (x *WebhookSubscribeAck) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookSubscribeAck.ProtoReflect.Descriptor instead.
func (*WebhookSubscribeAck) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{19}
}

func (x *WebhookSubscribeAck) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

type WebhookEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // JSON-encoded {body, headers, query, params, path}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookEvent) Reset() {
	*x = WebhookEvent{}
	mi := &file_engine_v1_engine_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookEvent) ProtoMessage() {}

func (x *WebhookEvent) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookEvent.ProtoReflect.Descriptor instead.
func (*WebhookEvent) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{20}
}

func (x *WebhookEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WebhookEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *WebhookEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_engine_v1_engine_proto protoreflect.FileDescriptor

const file_engine_v1_engine_proto_rawDesc = "" +
	"\n" +
	"\x16engine/v1/engine.proto\x12\tengine.v1\"=\n" +
	"\x0eConnectRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x11\n" +
	"\x0fConnectResponse\"*\n" +
	"\x11DisconnectRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"\x14\n" +
	"\x12DisconnectResponse\"\x95\x03\n" +
	"\x0eExecuteRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12#\n" +
	"\rendpoint_name\x18\x03 \x01(\tR\fendpointName\x12\x16\n" +
	"\x06params\x18\x04 \x01(\fR\x06params\x12L\n" +
	"\vcredentials\x18\x05 \x03(\v2*.engine.v1.ExecuteRequest.CredentialsEntryR\vcredentials\x12 \n" +
	"\venvironment\x18\x06 \x01(\tR\venvironment\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\x12*\n" +
	"\x11request_body_hash\x18\b \x01(\tR\x0frequestBodyHash\x1a>\n" +
	"\x10CredentialsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\t\x10\n" +
	"R\x0eretry_override\"`\n" +
	"\x0fExecuteResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\x05R\n" +
	"statusCode\"\xff\x02\n" +
	"\x1aStartConnectSessionRequest\x12\x1b\n" +
	"\tbucket_id\x18\x01 \x01(\tR\bbucketId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12 \n" +
	"\fend_user_ref\x18\x03 \x01(\tR\n" +
	"endUserRef\x12\x1d\n" +
	"\n" +
	"return_url\x18\x04 \x01(\tR\treturnUrl\x12)\n" +
	"\x11created_by_app_id\x18\x05 \x01(\tR\x0ecreatedByAppId\x12_\n" +
	"\x0eresource_input\x18\x06 \x03(\v28.engine.v1.StartConnectSessionRequest.ResourceInputEntryR\rresourceInput\x12\x16\n" +
	"\x06scopes\x18\a \x03(\tR\x06scopes\x1a@\n" +
	"\x12ResourceInputEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"a\n" +
	"\x1bStartConnectSessionResponse\x12#\n" +
	"\rauthorize_url\x18\x01 \x01(\tR\fauthorizeUrl\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\";\n" +
	"\x14GetConnectionRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\"h\n" +
	"\x15GetConnectionResponse\x129\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2\x19.engine.v1.AuthConnectionR\n" +
	"connection\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\xaf\x04\n" +
	"\x0eAuthConnection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tbucket_id\x18\x02 \x01(\tR\bbucketId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x03 \x01(\tR\tserviceId\x12 \n" +
	"\fend_user_ref\x18\x04 \x01(\tR\n" +
	"endUserRef\x12)\n" +
	"\x11created_by_app_id\x18\x05 \x01(\tR\x0ecreatedByAppId\x12\x1b\n" +
	"\tauth_type\x18\x06 \x01(\tR\bauthType\x12\x1d\n" +
	"\n" +
	"token_type\x18\a \x01(\tR\ttokenType\x12\x16\n" +
	"\x06scopes\x18\b \x03(\tR\x06scopes\x12!\n" +
	"\fscope_source\x18\t \x01(\tR\vscopeSource\x12\x16\n" +
	"\x06issuer\x18\n" +
	" \x01(\tR\x06issuer\x12\x18\n" +
	"\asubject\x18\v \x01(\tR\asubject\x12\x1d\n" +
	"\n" +
	"expires_at\x18\f \x01(\tR\texpiresAt\x127\n" +
	"\x18refresh_token_expires_at\x18\r \x01(\tR\x15refreshTokenExpiresAt\x12 \n" +
	"\flast_used_at\x18\x0e \x01(\tR\n" +
	"lastUsedAt\x12#\n" +
	"\rrefresh_state\x18\x0f \x01(\tR\frefreshState\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\tR\tupdatedAt\"E\n" +
	"\x1eListConnectionResourcesRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\"^\n" +
	"\x1fListConnectionResourcesResponse\x12;\n" +
	"\tresources\x18\x01 \x03(\v2\x1d.engine.v1.ConnectionResourceR\tresources\"\xa5\x02\n" +
	"\x12ConnectionResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rconnection_id\x18\x02 \x01(\tR\fconnectionId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x03 \x01(\tR\tserviceId\x12#\n" +
	"\rresource_type\x18\x04 \x01(\tR\fresourceType\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\x12\x16\n" +
	"\x06scopes\x18\x06 \x03(\tR\x06scopes\x12\x1d\n" +
	"\n" +
	"is_default\x18\a \x01(\bR\tisDefault\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\xb7\x01\n" +
	"\x14WebhookClientMessage\x12;\n" +
	"\tsubscribe\x18\x01 \x01(\v2\x1b.engine.v1.WebhookSubscribeH\x00R\tsubscribe\x12)\n" +
	"\x03ack\x18\x02 \x01(\v2\x15.engine.v1.WebhookAckH\x00R\x03ack\x12,\n" +
	"\x04nack\x18\x03 \x01(\v2\x16.engine.v1.WebhookNackH\x00R\x04nackB\t\n" +
	"\apayload\"O\n" +
	"\x10WebhookSubscribe\x12#\n" +
	"\rreceiver_name\x18\x01 \x01(\tR\freceiverName\x12\x16\n" +
	"\x06events\x18\x02 \x03(\tR\x06events\"'\n" +
	"\n" +
	"WebhookAck\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"@\n" +
	"\vWebhookNack\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x94\x01\n" +
	"\x14WebhookServerMessage\x12@\n" +
	"\n" +
	"subscribed\x18\x01 \x01(\v2\x1e.engine.v1.WebhookSubscribeAckH\x00R\n" +
	"subscribed\x12/\n" +
	"\x05event\x18\x02 \x01(\v2\x17.engine.v1.WebhookEventH\x00R\x05eventB\t\n" +
	"\apayload\":\n" +
	"\x13WebhookSubscribeAck\x12#\n" +
	"\rreceiver_name\x18\x01 \x01(\tR\freceiverName\"N\n" +
	"\fWebhookEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload2\xe7\x04\n" +
	"\rEngineService\x12@\n" +
	"\aConnect\x12\x19.engine.v1.ConnectRequest\x1a\x1a.engine.v1.ConnectResponse\x12I\n" +
	"\n" +
	"Disconnect\x12\x1c.engine.v1.DisconnectRequest\x1a\x1d.engine.v1.DisconnectResponse\x12B\n" +
	"\aExecute\x12\x19.engine.v1.ExecuteRequest\x1a\x1a.engine.v1.ExecuteResponse0\x01\x12d\n" +
	"\x13StartConnectSession\x12%.engine.v1.StartConnectSessionRequest\x1a&.engine.v1.StartConnectSessionResponse\x12R\n" +
	"\rGetConnection\x12\x1f.engine.v1.GetConnectionRequest\x1a .engine.v1.GetConnectionResponse\x12p\n" +
	"\x17ListConnectionResources\x12).engine.v1.ListConnectionResourcesRequest\x1a*.engine.v1.ListConnectionResourcesResponse\x12Y\n" +
	"\x11SubscribeWebhooks\x12\x1f.engine.v1.WebhookClientMessage\x1a\x1f.engine.v1.WebhookServerMessage(\x010\x01B=Z;github.com/Usefused/engine/internal/engine/grpc/v1;enginev1b\x06proto3"

var (
	file_engine_v1_engine_proto_rawDescOnce sync.Once
	file_engine_v1_engine_proto_rawDescData []byte
)

func file_engine_v1_engine_proto_rawDescGZIP() []byte {
	file_engine_v1_engine_proto_rawDescOnce.Do(func() {
		file_engine_v1_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engine_v1_engine_proto_rawDesc), len(file_engine_v1_engine_proto_rawDesc)))
	})
	return file_engine_v1_engine_proto_rawDescData
}

var file_engine_v1_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_engine_v1_engine_proto_goTypes = []any{
	(*ConnectRequest)(nil),                  // 0: engine.v1.ConnectRequest
	(*ConnectResponse)(nil),                 // 1: engine.v1.ConnectResponse
	(*DisconnectRequest)(nil),               // 2: engine.v1.DisconnectRequest
	(*DisconnectResponse)(nil),              // 3: engine.v1.DisconnectResponse
	(*ExecuteRequest)(nil),                  // 4: engine.v1.ExecuteRequest
	(*ExecuteResponse)(nil),                 // 5: engine.v1.ExecuteResponse
	(*StartConnectSessionRequest)(nil),      // 6: engine.v1.StartConnectSessionRequest
	(*StartConnectSessionResponse)(nil),     // 7: engine.v1.StartConnectSessionResponse
	(*GetConnectionRequest)(nil),            // 8: engine.v1.GetConnectionRequest
	(*GetConnectionResponse)(nil),           // 9: engine.v1.GetConnectionResponse
	(*AuthConnection)(nil),                  // 10: engine.v1.AuthConnection
	(*ListConnectionResourcesRequest)(nil),  // 11: engine.v1.ListConnectionResourcesRequest
	(*ListConnectionResourcesResponse)(nil), // 12: engine.v1.ListConnectionResourcesResponse
	(*ConnectionResource)(nil),              // 13: engine.v1.ConnectionResource
	(*WebhookClientMessage)(nil),            // 14: engine.v1.WebhookClientMessage
	(*WebhookSubscribe)(nil),                // 15: engine.v1.WebhookSubscribe
	(*WebhookAck)(nil),                      // 16: engine.v1.WebhookAck
	(*WebhookNack)(nil),                     // 17: engine.v1.WebhookNack
	(*WebhookServerMessage)(nil),            // 18: engine.v1.WebhookServerMessage
	(*WebhookSubscribeAck)(nil),             // 19: engine.v1.WebhookSubscribeAck
	(*WebhookEvent)(nil),                    // 20: engine.v1.WebhookEvent
	nil,                                     // 21: engine.v1.ExecuteRequest.CredentialsEntry
	nil,                                     // 22: engine.v1.StartConnectSessionRequest.ResourceInputEntry
}
var file_engine_v1_engine_proto_depIdxs = []int32{
	21, // 0: engine.v1.ExecuteRequest.credentials:type_name -> engine.v1.ExecuteRequest.CredentialsEntry
	22, // 1: engine.v1.StartConnectSessionRequest.resource_input:type_name -> engine.v1.StartConnectSessionRequest.ResourceInputEntry
	10, // 2: engine.v1.GetConnectionResponse.connection:type_name -> engine.v1.AuthConnection
	13, // 3: engine.v1.ListConnectionResourcesResponse.resources:type_name -> engine.v1.ConnectionResource
	15, // 4: engine.v1.WebhookClientMessage.subscribe:type_name -> engine.v1.WebhookSubscribe
	16, // 5: engine.v1.WebhookClientMessage.ack:type_name -> engine.v1.WebhookAck
	17, // 6: engine.v1.WebhookClientMessage.nack:type_name -> engine.v1.WebhookNack
	19, // 7: engine.v1.WebhookServerMessage.subscribed:type_name -> engine.v1.WebhookSubscribeAck
	20, // 8: engine.v1.WebhookServerMessage.event:type_name -> engine.v1.WebhookEvent
	0,  // 9: engine.v1.EngineService.Connect:input_type -> engine.v1.ConnectRequest
	2,  // 10: engine.v1.EngineService.Disconnect:input_type -> engine.v1.DisconnectRequest
	4,  // 11: engine.v1.EngineService.Execute:input_type -> engine.v1.ExecuteRequest
	6,  // 12: engine.v1.EngineService.StartConnectSession:input_type -> engine.v1.StartConnectSessionRequest
	8,  // 13: engine.v1.EngineService.GetConnection:input_type -> engine.v1.GetConnectionRequest
	11, // 14: engine.v1.EngineService.ListConnectionResources:input_type -> engine.v1.ListConnectionResourcesRequest
	14, // 15: engine.v1.EngineService.SubscribeWebhooks:input_type -> engine.v1.WebhookClientMessage
	1,  // 16: engine.v1.EngineService.Connect:output_type -> engine.v1.ConnectResponse
	3,  // 17: engine.v1.EngineService.Disconnect:output_type -> engine.v1.DisconnectResponse
	5,  // 18: engine.v1.EngineService.Execute:output_type -> engine.v1.ExecuteResponse
	7,  // 19: engine.v1.EngineService.StartConnectSession:output_type -> engine.v1.StartConnectSessionResponse
	9,  // 20: engine.v1.EngineService.GetConnection:output_type -> engine.v1.GetConnectionResponse
	12, // 21: engine.v1.EngineService.ListConnectionResources:output_type -> engine.v1.ListConnectionResourcesResponse
	18, // 22: engine.v1.EngineService.SubscribeWebhooks:output_type -> engine.v1.WebhookServerMessage
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_engine_v1_engine_proto_init() }
func file_engine_v1_engine_proto_init() {
	if File_engine_v1_engine_proto != nil {
		return
	}
	file_engine_v1_engine_proto_msgTypes[14].OneofWrappers = []any{
		(*WebhookClientMessage_Subscribe)(nil),
		(*WebhookClientMessage_Ack)(nil),
		(*WebhookClientMessage_Nack)(nil),
	}
	file_engine_v1_engine_proto_msgTypes[18].OneofWrappers = []any{
		(*WebhookServerMessage_Subscribed)(nil),
		(*WebhookServerMessage_Event)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engine_v1_engine_proto_rawDesc), len(file_engine_v1_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_engine_v1_engine_proto_goTypes,
		DependencyIndexes: file_engine_v1_engine_proto_depIdxs,
		MessageInfos:      file_engine_v1_engine_proto_msgTypes,
	}.Build()
	File_engine_v1_engine_proto = out.File
	file_engine_v1_engine_proto_goTypes = nil
	file_engine_v1_engine_proto_depIdxs = nil
}
